# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "bento/centos-7.3"

  config.vm.hostname = "centos73.vagrant.dev"

  # Enable provisioning with a shell script.
  config.vm.provision "shell", inline: <<-SHELL
    yum install -y vim
    echo "set background=dark" > /home/vagrant/.vimrc
    ln -s /vagrant/prereq-check.sh
  SHELL
end
